
[project]
name = "photobooth-wigglecam"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "michael", email = "me@mgineer85.de"},
]
requires-python = ">=3.10,<3.14"

dependencies = [
    "opencv-python>=4.8.1",
    "numpy>=1.26.0",
    "pillow>=10.0.0",
    "psutil>=5.9.0",
]

[tool.pdm.dev-dependencies]
test = [
  "pytest>=7.4.0",
  "pytest-benchmark>=4.0.0",
]
lint = ["ruff>=0.1.8"]

[project.scripts]
wigglify = "wigglify.cli:main"
wigglecam_main = "wigglecam.primary"
wigglecam_sub = "wigglecam.secondary"

[tool.pdm.scripts]
test = "pytest --basetemp=./tests_tmp/ -v ./tests"


[tool.ruff]
line-length = 150
extend-exclude = ["vendor"]
target-version = "py39"

[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "W",  # pycodestyle
  "F",  # pyflakes
  "B",  # bugbear
  "UP", # pyupgrade
  "I",  # isort
  #"D",   # pydocstyle   # add later
]
ignore = [
  "B008", #used for DI injection
]

[tool.ruff.lint.pydocstyle]
convention = "google"



[tool.pytest.ini_options]
testpaths = "tests"
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm.build]
includes = ["./wigglify"]
